### PR TITLE
Update release and default endpoints.

### PR DESCRIPTION
**Pull request by marc0der**

### CODE REVIEW

**Comment by aalmiray** [comment]
LGTM. I guess JReleaser needs an update as well. I suppose old endpoints will remain active for a while?

**Comment by marc0der** [comment]
Feel free to update the JReleaser version @aalmiray 👍

**Comment by aalmiray** [comment]
Are the new endpoints live these days?

**Comment by marc0der** [comment]
Yep, they are already live and the old ones will remain available for backwards compatibility.

**Pull request merged**
